export { default as Html } from './Html.png';
export { default as Css } from './CSS.png';
export { default as Javascript } from './Javascript.png';
export { default as NextJS } from './NextJS.png';
export { default as React } from './React.png';
export { default as Tailwind } from './Tailwind.png';
export { default as Typescript } from './Typescript.png';
export { default as Amplify } from './Amplify.png';
export { default as EC2 } from './EC2.png';
export { default as MongoDB } from './MongoDB.png';
export { default as Mysql } from './Mysql.png';
export { default as NestJS } from './NestJS.png';
export { default as NodeJS } from './nodejs.png';
export { default as Solidity } from './Solidity.png';
export { default as NFT } from './Main.gif';
export { default as GptMusic } from './GptMusic.gif';
export { default as Nodephl } from './PHL.gif';
export { default as Clone } from './Clone.gif';
export { default as nft } from './NFT.png'
export { default as gptMusic } from './GptMusic.png'
export { default as phl } from './PHL.png'
export { default as clone } from './Clone.png'